spring:
  application:
    name: game-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/game_backend}
    username: ${DB_USERNAME:game}
    password: ${DB_PASSWORD:game}
  jackson:
    time-zone: UTC
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

app:
  auth:
    token-ttl-hours: 2400
  random-service:
    base-url: ${RANDOM_SERVICE_URL:http://localhost:9095}
