spring:
  application:
    name: game-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/game_backend}
    username: ${DB_USERNAME:game}
    password: ${DB_PASSWORD:game}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

server:
  port: 8081

app:
  auth:
    token-ttl-hours: 2400
